inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-2.4, 2.],[-0.6, 2.9],[-1.8, 3.1]]
  marching_cubes_bound: [[-2.4, 2.],[-0.6, 2.9],[-1.8, 3.1]]
  
data:
  dataset: 'synthetic'
  datadir: Datasets/breakfast_room
  output: output/Synthetic/br
  downsample: 1

cam:
  near: 0
  far: 5