inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-2.5, 1.1],[-0.3, 1.1],[0.1, 3.9]]
  marching_cubes_bound: [[-2.5, 1.1],[-0.3, 1.1],[0.1, 3.9]]
  
data:
  dataset: 'synthetic'
  datadir: Datasets/thin_geometry
  output: output/Synthetic/tg
  downsample: 1

cam:
  near: 0
  far: 4