inherit_from: configs/Synthetic/synthetic.yaml
mapping:
  bound: [[-2.6, 3.2],[-0.4, 3.6],[0.5, 8.3]]
  marching_cubes_bound: [[-2.6, 3.2],[-0.4, 3.6],[0.5, 8.3]]
  
data:
  dataset: 'synthetic'
  datadir: Datasets/whiteroom
  output: output/Synthetic/w
  downsample: 1

cam:
  near: 0
  far: 8